title: Joseph Cassano (JPLC)
description: The personal website of Joseph Cassano (sometimes known as JPLC).
email: joseph.cassano@jplc.ca
emailWritten: joseph DOT cassano AT jplc DOT ca
firstName: Joseph
lastName: Cassano
nickname: JPLC
linkedInUrl: https://www.linkedin.com/in/josephcassano
